terminate called after throwing an instance of 'std::runtime_error'
  what():  Iterator's operation exceeded bounds
../../../cosi/timecmd.sh: line 106: 19615 Aborted                 (core dumped) $TIMEOUTCMD $REST > $OUTFILE 2> $ERRFILE

real	1m9.913s
user	1m1.121s
sys	0m1.315s
retcode 134
host node1378
