terminate called after throwing an instance of 'std::runtime_error'
  what():  Iterator's operation exceeded bounds
../../../cosi/timecmd.sh: line 106:  4803 Aborted                 (core dumped) $TIMEOUTCMD $REST > $OUTFILE 2> $ERRFILE

real	9m4.379s
user	8m23.114s
sys	0m4.861s
retcode 134
host node1378
